konexbvc/konexbvc/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^tramites/', include('tramites.urls')),
    url(r'^admin/', admin.site.urls),
]

konexbvc/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^tramites/', include('tramites.urls')),
    url(r'^admin/', admin.site.urls),
]

tramites/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from . import views
app_name = 'Konexbvc'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^registrarTramite$', views.TramitesView.as_view(), name='registrar_tramite'),
]

tramites/models.py
from django.db import models

# Create your models here.
class Tramite(models.Model):
    TRAMITES_CHOICES = [
        ('DONACION', 'Donación'),
        ('SUCESION', 'Sucesión'),
        ('ACT_DATO', 'Actualización datos')
    ]
    PREFERENCIA_CHOICES = [
        ('CORREO', 'Correo'),
        ('FISICO', 'Dirección Fisioa')
    ]
    ESTADO_CHOICES = [
        ('REGISTRADO', 'Registrado'),
        ('ASESOR', 'Asignado a un asesor'),
        ('TECNICO', 'Asignado a un soporte técnico'),
        ('SOLUCIONADO', 'Solucionado')
    ]
    nombre = models.CharField(max_length=200)
    correo = models.CharField(max_length=300)
    tramite = models.CharField(max_length=8, choices=TRAMITES_CHOICES)
    comunicacion = models.CharField(max_length=6, choices=PREFERENCIA_CHOICES)
    solicitud = models.CharField(max_length=2000)
    estado = models.CharField(max_length=11, choices=ESTADO_CHOICES)

tramites/forms.py
from django import forms
from .models import Tramite

class TramiteForm(forms.ModelForm):
    class Meta:
        model = Tramite

        fields = [
            'nombre',
            'correo',
            'tramite',
            'comunicacion',
            'solicitud',
        ]
        labels = {
            'nombre': 'Nombres',
            'correo': 'Correo',
            'tramite': 'Trámite',
            'comunicacion': 'Preferencia Comunicación',
            'solicitud': 'Solicitud',
        }
        widgets = {

        }

tramites/views.py
from django.shortcuts import render

from django.shortcuts import get_object_or_404
from django.views.generic import *
from .models import *
from django.views.generic import CreateView
from django.urls import reverse
from .forms import TramiteForm
# Create your views here.


class IndexView(ListView):
    template_name = 'tramites/index.html'
    context_object_name = 'mensaje'
    #queryset = Personaje.objects.all()
    #serializer_class = DeporteSerializer

    def get_queryset(self):
        return "Pagina inicial"

class TramitesView(CreateView):
    model = Tramite
    template_name = "tramites/registrarTramite.html"
    form_class = TramiteForm
    #success_url = reverse('konexbvc:index')

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super(TramitesView, self).form_valid(form)

tramites/templates/tramites/index.html
<html>
{% load static %}
{# load the tag library #}
{% load bootstrap3 %}

{# load css and javascript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

<div class="panel panel-primary" >
<h1 align="center">Konexbvc</h1>
</div>
<h3>{{mensaje}}</h3>

tramites/templates/tramites/registrarTramite.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
{# load the tag library #}
{% load bootstrap3 %}

{# load css and javascript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

</head>
<body>
<div class="panel panel-primary" >
    <h1 align="center">Konexbvc</h1>
    <h3 align="center">Registra tu trámite aqui:</h3>
</div>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-success" type="submit">Guardar</button>
    <a class="btn btn-default" href="{%  url 'Konexbvc:index' %}">Cancelar</a>
</form>
</body>
</html>